version: "3.9"
services:
  image-classifier-model:
    image: image-classifier-model:v1
  gateway:
    image: image-classifier-gateway:v1
    environment:
      - TF_SERVING_HOST=image-classifier-model:8500
    ports:
      - "9696:9696"